### ISSUE TITLE
[BUG] .exe causes virus alert

### ISSUE THREAD

**Issue by mach0** [totalopenstation/totalopenstation#140]
**Describe the bug**
The current exe release for Windows. Downloaded from
https://github.com/totalopenstation/totalopenstation/releases/download/v0.5.2/totalopenstation_x64_0.5.2.exe
causes some Antivirus programs to deny downloading because of an alert.

**To Reproduce**
Download on a Windows10 PV with for e.g. Avira activated or upload exe to virustotal which also shows 3 positives
https://www.virustotal.com/gui/file/60c1e2b181fb85238423f033d7645e618c5ad64e654df83a16ffa05509564e14/detection

**Expected behavior**
No alert, download and installable exe on Windoes

**Comment by psolyca** [comment]
It is a known feature of windows : https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher.

We have to sign our executable : https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

**Comment by steko** [comment]
Since the .exe is generated with PyInstaller, the reference for this issue is described here https://github.com/pyinstaller/pyinstaller/issues/4633 

Of course it's a false positive: the .exe is generated by GitHub (owned by Microsoft) on their servers with an official Windows environment.

Proposed solutions:

- [x] contact antivirus company and let them know this is not a virus
- [ ] add a disclaimer to the download page
- [ ] offer a zip bundle as alternative (possibly this will not be marked as virus)

The Windows Defender / code signing issue is probably related but separate, I think? It's worth investigating as @psolyca did

**Comment by steko** [comment]
I submitted the 0.5.2 .exe using the form at https://www.secureaplus.com/features/antivirus/report-false-positive/ (since SecureAge APEX is the only red flag in the VirusTotal report).

**Comment by steko** [comment]
I got a positive response from SecureAPlus

> Hello,
>
>Your submission (20201201-224956239000/totalopenstation.zip) has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us at secureaplus@secureage.com if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result.
> 
> Thank you for your report.
>
>SecureAPlus Admin

**Comment by steko** [comment]
VirusTotal now shows all green flags

![immagine](https://user-images.githubusercontent.com/40545/101167521-4cd59180-363a-11eb-95f8-3e88561c2faf.png)

I don't know if this has immediate effect on desktop antivirus software like Avira.

**Comment by mach0** [comment]
I don't know which virustool my colleague is using,  but I am going to ask him to check again.
