### ISSUE TITLE
TypeError: argument of type 'float' is not iterable

### ISSUE THREAD

**Issue by diffendale** [totalopenstation/totalopenstation#53]
This is what happens when I try to run totalopenstation-gui.py (sorry for the mess; the cmd window opens and closes very quickly, and this was the only way I could screen-capture it):
![totalopenstation problem - copy](https://cloud.githubusercontent.com/assets/12320564/8316243/05b6c8ca-19f6-11e5-8590-3039ae3fd195.PNG)

I'm a complete and total novice at Python, so I'm not sure if this is an issue on my end or yours...
Running Windows 7 (64 bit), Python 2.7.10...

**Comment by steko** [comment]
Thanks for reporting this issue. I'm looking into it, that's definitely a bug on our side!

More specifically, we're passing a float argument to ConfigParser, but it only accepts strings.

Could you check if there is a `.totalopenstation` directory in`c:\users\diffendale`?

**Comment by diffendale** [comment]
Ok! 

Yes, there is a <code>.totalopenstation</code> directory in <code>c:\users\diffendale</code>. It contains <code>totalopenstation.cfg</code>.

**Comment by steko** [comment]
As a temporary workaround, you can put this in the `totalopenstation.cfg` file:

```
[topsconfig]
model =
port =
sleeptime = 1.0
```

A fix will be included in the next release.

**Comment by diffendale** [comment]
That works, thank you!

**Comment by steko** [comment]
Good to know, thanks. We will update on the bug as soon as a fix is ready.

**Comment by colinjara** [comment]
I am having the same error in a Mac OS X (10.10.3) virtual environment. 
I have found the pref.py file that I assume contains the preferences for the virtual environment, rather than the above totalopenstation.cfg file. Where do I put in the lines that you mentioned? I too am incredibly new at Python, with little knowledge as to the proper syntax. 

Thank you! 

I will continue trying things until I hear back. 
<img width="949" alt="screen shot 2015-07-10 at 2 01 37 pm" src="https://cloud.githubusercontent.com/assets/13274187/8619139/3a574758-270c-11e5-8338-8fd8e7b8a7d3.png">

**Comment by steko** [comment]
Colin, on Mac OS X the totalopenstation.cfg file should be found at `/home/colinjaramillo/.totalopenstation/totalopenstation.cfg`. Can you confirm that you can find the file and that you are able to use Total Open Station normally after fixing the file content?

I'm sorry it's taking so long to fix this bug but I'm currently doing fieldwork in Crete.

**Comment by colinjara** [comment]
<img width="482" alt="screen shot 2015-07-12 at 4 38 17 pm" src="https://cloud.githubusercontent.com/assets/13274187/8638479/785ecce8-28b4-11e5-8b47-15e64e007e30.png">
Steko,

I can't seem to find the file in the path you mentioned. I can open the file directory /home/ through the terminal but there is nothing in there whatsoever. The closest thing was the file I mentioned earlier, pref.py, but nothing by the name of totalopenstation.cfg. The path for that is /Users/colinjaramillo/tops-environment/lib/python2.7/site-packages/totalopenstation/utils/upref.py

No worries at all, I am doing fieldwork in Ireland myself and since I am deep in the country side there is little internet access.

I attached an image of the code that is similar to what you were describing for the totalopenstation.cfg.

**Comment by steko** [comment]
Fixed in 388b27a0cdf3aa1369c1c329cd61dfeb57b09ac6 - v0.3.2 is available on PyPI at https://pypi.python.org/pypi/totalopenstation

Thank you for reporting the issue.
